[package]
name = "aider_ledger_lab"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
chrono = "0.4.22"
uuid = { version = "1.1.2", features = ["v4"] }
rust_decimal = "1.26.1"
rusty_money = "0.4.1"
